export const enum CheckoutPhase {
    QUANTITY_VERIFICATION = "CHECKOUT_PHASE_QUANTITY_VERIFICATION",
    VALIDATE_CREDIT_CARD = "CHECKOUT_PHASE_VALIDATE_CREDIT_CARD",
    PURCHASE_FINALIZATION = "CHECKOUT_PHASE_PURCHASE_FINALIZATION",
    ERROR = "CHECKOUT_PHASE_ERROR",
    SUCCESS = 'CHECKOUT_PHASE_SUCCESS'
}

export const enum Page {
    CHECKOUT ="/checkout",
    HOME='/'
}
